version: "3.8"

services:

  database:
    container_name: movielens-database
    environment:
      - POSTGRES_DB=movielens
      - POSTGRES_USER=movielens
      - POSTGRES_PASSWORD=movielens
    image: postgres:14.5
    ports:
      - "5433:5432"
    volumes:
      - movielens-database:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: movielens-server
    depends_on:
      - database
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=movielens
      - SQL_USER=movielens
      - SQL_PASSWORD=movielens
      - SQL_HOST=movielens-database
      - SQL_PORT=5432
    command: [ "bash", "start.sh" ]
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app

volumes:
  movielens-database: